SELECT crypt('holanda', gen_salt('md5'));


INSERT INTO CIUDADES VALUES (1, 100, '100', 'ciudad a', crypt('holanda', gen_salt('md5')));

SELECT * FROM CIUDADES;
SELECT * FROM EMPLEADOS;

SELECT 'x' AS pswmatch FROM CIUDADES WHERE psw = crypt('holanda', psw);

SELECT SESSION_USER, CURRENT_USER;

SET ROLE 'ROLKIOSKO';
SET ROLE 'postgres';

CREATE ROLE ROLKIOSKO WITH PASSWORD 'RLKSK';

GRANT SELECT, UPDATE, INSERT, DELETE ON ciudades TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON conexioneskioskos TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON conficorreokiosko TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON empleados TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON empresas TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON generaleskiosko TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON opcioneskioskos TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON parametrizaclave TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON personas TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON preguntaskioskos TO "ROLKIOSKO";
GRANT SELECT, UPDATE, INSERT, DELETE ON tiposdocumentos TO "ROLKIOSKO";

EMPLEADO: 561423